const images = {
  logo: require("../images/logo.png").default,
  plus: require("../images/plus_five.png").default,
  floatLogo: require("../images/flat_logo.png").default,
  user12: require("../images/user.png").default,
  logohome: require("../images/logoone.png").default,
  oyster: require("../images/oyster11.jpg").default,
  travel: require("../images/travel11.png").default,
  // oyster: require('../images/oyster.gif').default,
  // travel: require('../images/travel.gif').default,
  shopping: require("../images/shopping.jpg").default,
  banner1: require("../images/banner1.png").default,
  banner2: require("../images/banner2.png").default,
  banner3: require("../images/banner3.png").default,
  border1: require("../images/border1.png").default,
  mobile: require("../images/mobile.png").default,
  background: require("../images/background.png").default,
  box1: require("../images/box1.png").default,
  cashpay1: require("../images/cash-pay1.png").default,
  global1: require("../images/global1.png").default,
  maskvalue: require("../images/mask-value.png").default,
  ticket: require("../images/ticket.png").default,
  bag: require("../images/bags.png").default,
  heart: require("../images/heart.png").default,
  cursor: require("../images/cursor1.png").default,
  fb: require("../images/fb 1.png").default,
  tw: require("../images/tw 1.png").default,
  youtube: require("../images/youtube 1.png").default,
  mobilecut: require("../images/mobile-cut.png").default,
  taxicut: require("../images/taxi.png").default,
  location: require("../images/location 1.png").default,
  choose: require("../images/choose 1.png").default,
  train1: require("../images/train 1.png").default,
  cycle: require("../images/cycle.png").default,
  passenger: require("../images/passenger.png").default,
  link: require("../images/lin.png").default,
  img: require("../images/img.png").default,
  img1: require("../images/img1.png").default,
  img2: require("../images/img2.png").default,
  img3: require("../images/img3.png").default,
  finance: require("../images/finance.png").default,
  tech12: require("../images/tech12.png").default,
  development: require("../images/development 1.png").default,
  operation: require("../images/operation 2.png").default,
  plan1: require("../images/plan1.png").default,
  plan2: require("../images/plan2.png").default,
  plan3: require("../images/plan3.png").default,
  plan4: require("../images/plan4.png").default,
  plan5: require("../images/plan5.png").default,
  plan6: require("../images/plan6.png").default,
  gifticon: require("../images/gift-icon1.png").default,
  banker: require("../images/banker.png").default,
  eye: require("../images/eyee.png").default,
  arrow: require("../images/arrow.png").default,
  up: require("../images/drop-1.png").default,
  view: require("../images/view.png").default,
  train: require("../images/train.png").default,
  recent: require("../images/recent.png").default,
  top: require("../images/top.png").default,
  text_1: require("../images/text_1.png").default,
  el_phone: require("../images/el_phone.png").default,
  entypo_address: require("../images/entypo_address.png").default,
  wpf_name1: require("../images/wpf_name.png").default,
  cancel: require("../images/ic_round-cancel.png").default,
  loginimage: require("../images/login-image.png").default,
  thankyou: require("../images/thankyou.png").default,
  trainout: require("../images/train-out.png").default,
  shiptruck: require("../images/shiptruck.png").default,
  tool: require("../images/tool.png").default,
  catchpa: require("../images/catchpa.png").default,
  back: require("../images/back.png").default,
  unmask: require("../images/unmask.png").default,
  line_t: require("../images/line_t.png").default,
  linkdin: require("../images/lin.png").default,
  first_f: require("../images/first_f.png").default,
  second_f: require("../images/second_f.png").default,
  mask_1: require("../images/mask_1.jpeg").default,
  mask_2: require("../images/mask_2.jpeg").default,
  about1: require("../images/about2.png").default,
  about2: require("../images/about1.jpg").default,
  contact: require("../images/contact.jpeg").default,
  price: require("../images/chart.jpg").default,
  finance1: require("../images/finance1.png").default,
  payment: require("../images/payment.png").default,
  chat: require("../images/chat.png").default,
};

export default images;
